AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: container_demo
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
  AWSRegionArch2AMI:
    ap-northeast-1:
      HVM64: ami-06cd52961ce9f0d85
    ap-northeast-2:
      HVM64: ami-0a10b2721688ce9d2
    ap-northeast-3:
      HVM64: ami-0d98120a9fb693f07
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
    ap-southeast-2:
      HVM64: ami-09b42976632b27e9b
    ap-south-1:
      HVM64: ami-0912f71e06545ad88
Metadata:
  'AWS::CloudFormation::Designer':
    aab8ee15-d932-4b72-8015-421bb7b226ff:
      size:
        width: 490
        height: 220
      position:
        x: -240
        'y': 20
      z: 0
      embeds:
        - f850a4a3-c01b-4120-8aae-588cc4e7ed87
    f850a4a3-c01b-4120-8aae-588cc4e7ed87:
      size:
        width: 140
        height: 140
      position:
        x: -200
        'y': 70
      z: 1
      parent: aab8ee15-d932-4b72-8015-421bb7b226ff
      embeds:
        - 5a8b4b14-a371-428a-8936-ca39fbce258f
      iscontainedinside:
        - aab8ee15-d932-4b72-8015-421bb7b226ff
    5a8b4b14-a371-428a-8936-ca39fbce258f:
      size:
        width: 60
        height: 60
      position:
        x: -160
        'y': 110
      z: 2
      parent: f850a4a3-c01b-4120-8aae-588cc4e7ed87
      embeds: []
      iscontainedinside:
        - f850a4a3-c01b-4120-8aae-588cc4e7ed87
        - f850a4a3-c01b-4120-8aae-588cc4e7ed87
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
        CidrBlock: 10.0.0.0/16
        Tags:
            - Key: "Name"
              Value: "VPC"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: aab8ee15-d932-4b72-8015-421bb7b226ff
  SUBNET:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: "Name"
          Value: "SUBNET"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f850a4a3-c01b-4120-8aae-588cc4e7ed87
  INSTANCE:
    Type: 'AWS::EC2::Instance'
    Properties:
        InstanceType: !Ref InstanceType
        ImageId: !FindInMap
          - AWSRegionArch2AMI
          - !Ref 'AWS::Region'
          - !FindInMap
            - AWSInstanceType2Arch
            - !Ref InstanceType
            - Arch
        KeyName: !Ref KeyName
        SubnetId: !Ref SUBNET
        Tags:
          - Key: "Name"
            Value: "INSTANCE"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5a8b4b14-a371-428a-8936-ca39fbce258f
